### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by legobmw99** [ZenDarva/Allomancy#3]
I have no better way of contacting you, do I guess this works. I was wondering if you have plans to release the mod on the MCForums or anything, or if you'd be willing to give me permission to.

**Comment by ZenDarva** [comment]
You've put in as much work, if not more, on this as I have.  _laughs_  You
are fully free to release it as you wish.  I am looking at updating it to
1.7.2.

**Comment by legobmw99** [comment]
The 1.7.2 update is so big you pretty much rewrite the mod. For a mod of this size I figured it would be easier to literally rewrite the mod. I made a start here https://github.com/legobmw99/Allomancy/tree/Experimental but didn't get too far

**Comment by legobmw99** [comment]
I guess I'm going to release it. Do you have a license in mind for the source code / redistribution? I think the GPL/LGPL would be best (http://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License), but you should decide
Do you think it would be a good idea to make an organization so we could both contribute to the _same_ repo?

**Comment by ZenDarva** [comment]
I am fine with the GPL license.  The LGPL seems nonsensical in this
context.  I do tend towards the MIT license for most of my work, but GPL
seems better here, as neither of us actually own the rights to Allomancy
itself.  (I'd make sure to reference that somewhere!!)

**Comment by legobmw99** [comment]
I didn't even think to mention Allomancy wasn't originally our idea. I'll be sure to do that. Any thoughts on the organization idea? Github has made them real easy recently

**Comment by legobmw99** [comment]
Also, it sounds like the LGPL covers modpacks where GPL doesn't ("Combined works" section under the LGPL)

**Comment by ZenDarva** [comment]
Combined works under the LGPL is for when you've linked the project as a
dependency for another project.  Forge doesn't do that, so it doesn't
really apply, as i understand it.

Organization idea? I must have missed that.

**Comment by legobmw99** [comment]
I suggested making a github organization so we can both commit to the same repo without having to worry about pulls or forks. I guess we could also use the collaborator feature
